# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-07-14 22:05+Mitteleuropäische Sommerzeit\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4077
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4087
msgid "Could not connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:259
msgid "Operating System not supported: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Copy old appdata to new folder failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Error: def win_pre1_check_app_dir()"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:285
msgid "Could not create app_dir: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:307
msgid "Select User-ID failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:370
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:373
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
msgid "Error: '%s' not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:399
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Error: def read_options_file"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Read config file failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:788
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:823
msgid "Could not read your Network Interfaces! Please install OpenVPN or check if your TAP-Adapter is really enabled and driver installed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:854
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:868
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:884
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:889
msgid "Invalid characters in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:905
msgid "Choose your External Network Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:923
msgid "No Network Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:938
msgid "Please select your User-ID!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1048
msgid "Choose App Theme"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1088
msgid "Disconnect %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1092
msgid "Connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1100
msgid "Remove AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1104
msgid "Set AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1119
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1511
msgid "[enabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1121
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1513
msgid "[disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1122
msgid "Load extended Server-View %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1135
msgid "Set Server-View Size [%sx%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1144
msgid "Refresh Window"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1162
msgid "Change DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1169
msgid "Primary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1179
msgid "Secondary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1212
msgid "Primary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1215
msgid "Set Primary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1221
msgid "Secondary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1224
msgid "Set Secondary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1316
msgid "Checking for Updates!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1319
msgid "Disconnected! Have a nice and anonymous day!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1333
msgid "Connecting to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1339
msgid "Testing connection to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1354
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1495
msgid "Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1502
msgid "Select Network Adapter"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1514
msgid "DEBUG Mode %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1523
msgid "Set App Theme [%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1535
msgid "IPv6 Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1539
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1543
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1561
msgid "Firewall"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1567
msgid "Restore Firewall Backups"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1589
msgid "Updates"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1593
msgid "Normal Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1597
msgid "Forced Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1607
msgid "Reset API Login"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1612
msgid "Clear Passphrase from RAM"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1616
msgid "Clear Passphrase from CFG"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1677
msgid " [ disconnect ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1720
msgid "Close Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1723
msgid "Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1733
msgid "Close Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1735
msgid "Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1745
msgid "Close Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1747
msgid "Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1758
msgid "About"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1766
msgid "Quit"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1808
msgid "oVPN Server Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1855
msgid "Certificates and Configs updated!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1855
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
msgid "oVPN Update OK!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1858
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1860
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1863
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1871
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
msgid "Error: def inThread_timer_check_certdl"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1858
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1860
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1863
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1871
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
msgid "oVPN Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
msgid "No update needed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2117
msgid "oVPN Server - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2189
msgid "oVPN Server [ %s ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2324
msgid "oVPN Account - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2344
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2346
msgid "No data loaded! Retry in few seconds..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2443
msgid "oVPN Settings - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2451
msgid ""
"Windows Firewall Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2458
msgid " Firewall "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2465
msgid ""
"Network Adapter Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2468
msgid " Network "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2475
msgid ""
"Update Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2478
msgid " Updates "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2496
msgid "Use Windows Firewall (default: ON) "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2526
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2557
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2585
msgid "Disable FW question on Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2613
msgid "Clear Rules on Connect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2633
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2663
msgid "Could not export Windows Firewall Backup!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2633
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2663
msgid "Error: Windows Firewall Backup failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2643
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2673
msgid "DNS Leak Protection (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2702
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2730
msgid "Update Configs on Start (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2755
msgid "Load Account Info (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3070
msgid "Error: Certs not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3070
msgid "Files missing: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Could not start Windows Firewall!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Error: def inThread_spawn_openvpn_process"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3402
msgid "Error: DNS restore 2nd"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3402
msgid "Error: Restore Secondary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3405
msgid "Error: DNS restore 1st"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3405
msgid "Error: Restore Primary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3468
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3501
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3501
msgid "Error: SSL CA Cert #1"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid "Error: SSL CA Cert #2"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid "Error: SSL CA Cert #3"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3696
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3720
msgid "Error: netsh.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3735
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3759
msgid "Error: route.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3775
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3787
msgid "ipconfig.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3823
msgid "Enter your Passphrase"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3828
msgid "Save Passphrase in File?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3834
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3910
msgid "Passphrase:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3888
msgid "oVPN.to Setup"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3889
msgid "Enter your oVPN.to Details"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3896
msgid "User-ID:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3903
msgid "API-Key:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3909
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3916
msgid "Repeat:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4028
msgid "Debug Mode Enabled"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4028
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4077
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4087
msgid "Error: Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4130
msgid "Server Window Size"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4134
msgid "Width (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4138
msgid "Height (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4142
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4198
msgid "Switched to IPv4+6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4198
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4216
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4216
msgid "Switched to IPv6+4"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4320
msgid "API requests on: %s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4320
msgid "Error: def API_REQUEST"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4332
msgid "Invalid User-ID / API-Key or Account expired."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4432
msgid "Error: def move_appdata"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4432
msgid "Move Userdata to new folder: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4468
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4477
msgid "Could not read Servers Protocol from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4489
msgid "Could not read Servers Cipher from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4515
msgid "Error: def load_ovpn_server"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4515
msgid "Load openVPN Server failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4687
msgid "Platform '%s' not supported"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4687
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4738
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4742
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4879
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4882
msgid "Error!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4703
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4705
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4712
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4712
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4778
msgid "Setup: openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4738
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4742
msgid "Failed remove file: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4778
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4779
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4831
msgid "Could not detect openVPN Version!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4855
msgid "Could not find openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4879
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4882
msgid "Invalid content '%s' in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4899
msgid "arch '%s' not supported!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5100
msgid "Quit oVPN.to Client"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5104
msgid "Do you really want to quit?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5170
msgid "Firewall Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5174
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5177
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5230
msgid "Error"
msgstr ""

