# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2016-07-15 04:52+Mitteleuropäische Sommerzeit\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4108
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4119
msgid "Could not connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:259
msgid "Operating System not supported: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Copy old appdata to new folder failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Error: def win_pre1_check_app_dir()"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:285
msgid "Could not create app_dir: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:307
msgid "Select User-ID failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:370
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:373
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
msgid "Error: '%s' not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:399
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:670
msgid "Error: def read_options_file"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:670
msgid "Read config file failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:798
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:833
msgid "Could not read your Network Interfaces! Please install OpenVPN or check if your TAP-Adapter is really enabled and driver installed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:864
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:878
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:894
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:899
msgid "Invalid characters in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:915
msgid "Choose your External Network Adapter!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:933
msgid "No Network Adapter found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:948
msgid "Please select your User-ID!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1058
msgid "Choose App Theme"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1098
msgid "Disconnect %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1102
msgid "Connect to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1110
msgid "Remove AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1114
msgid "Set AutoConnect: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1129
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1521
msgid "[enabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1131
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1523
msgid "[disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1132
msgid "Load extended Server-View %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1145
msgid "Set Server-View Size [%sx%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1152
msgid "Update every: %s seconds"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1172
msgid "Change DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1179
msgid "Primary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1189
msgid "Secondary DNS: %s (%s)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1222
msgid "Primary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1225
msgid "Set Primary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1231
msgid "Secondary DNS '%s' @ %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1234
msgid "Set Secondary DNS"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1326
msgid "Checking for Updates!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1329
msgid "Disconnected! Have a nice and anonymous day!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1343
msgid "Connecting to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1349
msgid "Testing connection to %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1364
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1505
msgid "Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1512
msgid "Select Network Adapter"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1524
msgid "DEBUG Mode %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1533
msgid "Set App Theme [%s]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1545
msgid "IPv6 Options"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1549
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1553
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1571
msgid "Firewall"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1577
msgid "Restore Firewall Backups"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1599
msgid "Updates"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1603
msgid "Normal Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1607
msgid "Forced Config Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1617
msgid "Reset API Login"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1622
msgid "Clear Passphrase from RAM"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1626
msgid "Clear Passphrase from CFG"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1687
msgid " [ disconnect ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1730
msgid "Close Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1733
msgid "Servers"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1743
msgid "Close Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1745
msgid "Account"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1755
msgid "Close Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1757
msgid "Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1768
msgid "About"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1776
msgid "Quit"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1818
msgid "oVPN Server Update"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
msgid "Certificates and Configs updated!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1878
msgid "oVPN Update OK!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1870
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1875
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1881
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1883
msgid "Error: def inThread_timer_check_certdl"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1870
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1875
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1881
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1883
msgid "oVPN Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1878
msgid "No update needed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2128
msgid "oVPN Server - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2200
msgid "oVPN Server [ %s ]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2336
msgid "oVPN Account - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2356
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2358
msgid "No data loaded! Retry in few seconds..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2455
msgid "oVPN Settings - %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2463
msgid ""
"Windows Firewall Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2470
msgid " Firewall "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2477
msgid ""
"Network Adapter Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2480
msgid " Network "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2487
msgid ""
"Update Settings\n"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2490
msgid " Updates "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2508
msgid "Use Windows Firewall (default: ON) "
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2538
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2569
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2597
msgid "Disable FW question on Quit (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2625
msgid "Clear Rules on Connect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2645
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2675
msgid "Could not export Windows Firewall Backup!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2645
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2675
msgid "Error: Windows Firewall Backup failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2655
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2685
msgid "DNS Leak Protection (default: ON)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2714
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2742
msgid "Update Configs on Start (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2767
msgid "Load Account Info (default: OFF)"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Error: Certs not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Files missing: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3122
msgid "Could not start Windows Firewall!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3122
msgid "Error: def inThread_spawn_openvpn_process"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3428
msgid "Error: DNS restore 2nd"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3428
msgid "Error: Restore Secondary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3431
msgid "Error: DNS restore 1st"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3431
msgid "Error: Restore Primary DNS to %s failed."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3494
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3527
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3527
msgid "Error: SSL CA Cert #1"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3530
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3530
msgid "Error: SSL CA Cert #2"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3533
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3533
msgid "Error: SSL CA Cert #3"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3722
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3746
msgid "Error: netsh.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3761
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3785
msgid "Error: route.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3801
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3813
msgid "ipconfig.exe not found!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3849
msgid "Enter your Passphrase"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3854
msgid "Save Passphrase in File?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3860
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3936
msgid "Passphrase:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3914
msgid "oVPN.to Setup"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3915
msgid "Enter your oVPN.to Details"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3922
msgid "User-ID:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3929
msgid "API-Key:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3935
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3942
msgid "Repeat:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4058
msgid "Debug Mode Enabled"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4058
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4108
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4119
msgid "Error: Update failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4165
msgid "Server Window Size"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4169
msgid "Width (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4173
msgid "Height (pixel):"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4177
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4225
msgid "Load Data every X seconds"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4229
msgid "seconds:"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4279
msgid "Switched to IPv4+6"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4279
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4298
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4298
msgid "Switched to IPv6+4"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4403
msgid "API requests on: %s failed!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4403
msgid "Error: def API_REQUEST"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4415
msgid "Invalid User-ID / API-Key or Account expired."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4518
msgid "Error: def move_appdata"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4518
msgid "Move Userdata to new folder: '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4554
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4563
msgid "Could not read Servers Protocol from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4575
msgid "Could not read Servers Cipher from config: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4601
msgid "Error: def load_ovpn_server"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4601
msgid "Load openVPN Server failed"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4775
msgid "Platform '%s' not supported"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4775
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4830
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4914
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4967
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4970
msgid "Error!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4791
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4793
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4800
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4800
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4866
msgid "Setup: openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4830
msgid "Failed remove file: %s"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4866
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4867
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4914
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4919
msgid "Could not detect openVPN Version!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4943
msgid "Could not find openVPN"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4967
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4970
msgid "Invalid content '%s' in '%s'"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4987
msgid "arch '%s' not supported!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5188
msgid "Quit oVPN.to Client"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5192
msgid "Do you really want to quit?"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5258
msgid "Firewall Settings"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5262
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5265
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5318
msgid "Error"
msgstr ""

