# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2016-07-15 10:48+0200\n"
"PO-Revision-Date: 2016-07-15 10:48+0200\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.8\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr "Update fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4173
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4184
msgid "Could not connect to %s"
msgstr "Verbindung zu %s fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:259
msgid "Operating System not supported: %s"
msgstr "Betriebssystem wird nicht unterstützt: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Copy old appdata to new folder failed!"
msgstr "Kopiere \"appdata\" in neues Verzeichnis fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Error: def win_pre1_check_app_dir()"
msgstr "Fehler: def win_pre1_check_app_dir()"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:285
msgid "Could not create app_dir: %s"
msgstr "Konnte App Verzeichnis nicht anlegen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:307
msgid "Select User-ID failed!"
msgstr "User-ID Auswahl fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:370
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:373
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
msgid "Error: '%s' not found!"
msgstr "Fehler: '%s' nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:399
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""
"Sperr Datei konnte nicht entfernt werden.\n"
"Sperr Datei selbst ist gesperrt. Läuft eine weitere oVPN Client Instanz?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""
"Anlegen von API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr "Erzeugen der Konfigurationsverzeichnisse fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:670
msgid "Error: def read_options_file"
msgstr "Fehler: def read_options_file"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:670
msgid "Read config file failed!"
msgstr "Lesen der Konfigurationsdatei fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:798
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with "
"Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""
"Konnte die Interfaces mit netsh.exe nicht auslesen. Kontaktiere support@ovpn."
"to mit Error-ID:\n"
"ADAPTERS[1]=(%s)\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:833
msgid ""
"Could not read your Network Interfaces! Please install OpenVPN or check if "
"your TAP-Adapter is really enabled and driver installed."
msgstr ""
"Konnte Netzwerk Adapter nicht auslesen! Bitte installiere openVPN oder "
"überprüfe ob der TAP Adapter installiert und aktiviert ist."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:864
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr "Kein openVPN TAP Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:878
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""
"Mehrere TAP Adapter gefunden!\n"
"\n"
"Bitte den zu benutzenden Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:894
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"Kein openVPN TAP Adapter gefunden!\n"
"Bitte openVPN installieren!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:899
msgid "Invalid characters in '%s'"
msgstr "Ungültige Zeichen in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:915
msgid "Choose your External Network Adapter!"
msgstr "Netzwerk Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:933
msgid "No Network Adapter found!"
msgstr "Keine Netzwerk Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:948
msgid "Please select your User-ID!"
msgstr "Bitte User-ID auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1058
msgid "Choose App Theme"
msgstr "App-Thema auswählen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1098
msgid "Disconnect %s"
msgstr "Trennen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1102
msgid "Connect to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1110
msgid "Remove AutoConnect: %s"
msgstr "Automatisch verbinden entfernen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1114
msgid "Set AutoConnect: %s"
msgstr "Setze automatisch verbinden: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1129
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1533
msgid "[enabled]"
msgstr "[Ein]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1131
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1535
msgid "[disabled]"
msgstr "[Aus]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1132
msgid "Load extended Server-View %s"
msgstr "Lade erweitertes Server Fenster %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1145
msgid "Set Server-View Size [%sx%s]"
msgstr "Setze Server Fenster Größe [%sx%s]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1152
msgid "Update every: %s seconds"
msgstr "Aktualisiere jede: %s Sekunden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1172
msgid "Change DNS"
msgstr "DNS wechseln"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1179
msgid "Primary DNS: %s (%s)"
msgstr "Primärer DNS: %s (%s)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1189
msgid "Secondary DNS: %s (%s)"
msgstr "Sekundärer DNS: %s (%s)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1222
msgid "Primary DNS '%s' @ %s"
msgstr "Primärer DNS '%s' @ %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1225
msgid "Set Primary DNS"
msgstr "Setze primären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1231
msgid "Secondary DNS '%s' @ %s"
msgstr "Sekundärer DNS '%s' @ %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1234
msgid "Set Secondary DNS"
msgstr "Setze sekundären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1338
msgid "Checking for Updates!"
msgstr "Nach Updates suchen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1341
msgid "Disconnected! Have a nice and anonymous day!"
msgstr "Nicht verbunden! Hab einen schönen und anonymen Tag!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1355
msgid "Connecting to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1361
msgid "Testing connection to %s"
msgstr "Teste Verbindung zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1376
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr "Verbunden zu %s [%s]:%s (%s) [ %s ] (%s / %s ms)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1517
msgid "Options"
msgstr "Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1524
msgid "Select Network Adapter"
msgstr "Netzwerk Adapter wählen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1536
msgid "DEBUG Mode %s"
msgstr "DEBUG Modus %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1545
msgid "Set App Theme [%s]"
msgstr "Setze App Thema [%s]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1557
msgid "IPv6 Options"
msgstr "IPv6 Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1561
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr "Auswählen: IPv4 Eintritt Server mit Ausgang nach IPv4 (standard)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1565
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr "Auswählen: IPv4 Eintritts Server mit Ausgang nach IPv4 + IPv6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1583
msgid "Firewall"
msgstr "Firewall"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1589
msgid "Restore Firewall Backups"
msgstr "Firewall Einstellungen wiederherstellen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1611
msgid "Updates"
msgstr "Updates"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1615
msgid "Normal Config Update"
msgstr "Normales Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1619
msgid "Forced Config Update"
msgstr "Erzwungenes Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1629
msgid "Reset API Login"
msgstr "API Login zurücksetzen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1634
msgid "Clear Passphrase from RAM"
msgstr "Passwort aus dem Speicher löschen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1638
msgid "Clear Passphrase from CFG"
msgstr "Passwort aus der Konfiguration löschen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1699
msgid " [ disconnect ]"
msgstr "[ trennen ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1742
msgid "Close Servers"
msgstr "Server Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1745
msgid "Servers"
msgstr "Server Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1755
msgid "Close Account"
msgstr "Konto Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1757
msgid "Account"
msgstr "Konto Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1767
msgid "Close Settings"
msgstr "Einstellungen schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1769
msgid "Settings"
msgstr "Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1780
msgid "About"
msgstr "Über"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1788
msgid "Quit"
msgstr "Beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1830
msgid "oVPN Server Update"
msgstr "oVPN Server Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1877
msgid "Certificates and Configs updated!"
msgstr "Zertifikate und Konfiguration erneuert!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1877
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1890
msgid "oVPN Update OK!"
msgstr "oVPN Update OK!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1880
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1882
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1885
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1887
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1893
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1895
msgid "Error: def inThread_timer_check_certdl"
msgstr "Fehler: def inThread_timer_check_certdl"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1880
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1882
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1885
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1887
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1893
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1895
msgid "oVPN Update failed"
msgstr "oVPN Update fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1890
msgid "No update needed!"
msgstr "Kein Update nötig!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2140
msgid "oVPN Server - %s"
msgstr "oVPN Server - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2212
msgid "oVPN Server [ %s ]"
msgstr "oVPN Server [ %s ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2348
msgid "oVPN Account - %s"
msgstr "oVPN Konto - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2368
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr "Einstellungen -> Updates: Lade Konto Informationen [AUS]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2370
msgid "No data loaded! Retry in few seconds..."
msgstr "Keine Daten geladen! Bitte in ein paar Sekunden erneut probieren..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2467
msgid "oVPN Settings - %s"
msgstr "oVPN Einstellungen - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2475
msgid "Windows Firewall Settings\n"
msgstr "Windows Firewall Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2482
msgid " Firewall "
msgstr " Firewall "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2489
msgid "Network Adapter Settings\n"
msgstr "Netzwerk Adapter Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2492
msgid " Network "
msgstr " Netzwerk "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2499
msgid "Update Settings\n"
msgstr "Update Einstellungen \n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2503
msgid " Updates "
msgstr " Updates "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2521
msgid "Use Windows Firewall (default: ON) "
msgstr "Windows Firewall benutzen (standard: EIN) "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2551
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr "TAP-Adapter ausgehend blocken (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2582
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr "Internet sperren bei Trennung oder Beenden (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2610
msgid "Disable FW question on Quit (default: ON)"
msgstr "Firewall Abfrage beim Beenden abschalten (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2638
msgid "Clear Rules on Connect (default: OFF)"
msgstr "Regeln beim Verbinden löschen (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2658
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2688
msgid "Could not export Windows Firewall Backup!"
msgstr "Konnte Windows Firewall Sicherung nicht exportieren!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2658
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2688
msgid "Error: Windows Firewall Backup failed"
msgstr "Fehler: Windows Firewall Sicherung fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2668
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr "Sicherung/Wiederherstellung bei Start und Beenden (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2698
msgid "DNS Leak Protection (default: ON)"
msgstr "DNS Leck Schutz (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2727
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr "Deaktiviere '%s' bei Trennung (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2755
msgid "Update Configs on Start (default: OFF)"
msgstr "Beim Start auf Konfig Update prüfen (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2780
msgid "Load Account Info (default: OFF)"
msgstr "Lade Konto Informationen (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2815
msgid "Load Server Info (default: OFF)"
msgstr "Lade Server Informationen (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3161
msgid "Error: Certs not found!"
msgstr "Fehler: Zertifikate nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3161
msgid "Files missing: '%s'"
msgstr "Fehlende Dateien: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3187
msgid "Could not start Windows Firewall!"
msgstr "Konnte die Windows Firewall nicht starten!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3187
msgid "Error: def inThread_spawn_openvpn_process"
msgstr "Fehler: def inThread_spawn_openvpn_process"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3493
msgid "Error: DNS restore 2nd"
msgstr "Fehler: DNS Wiederherstellung 2."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3493
msgid "Error: Restore Secondary DNS to %s failed."
msgstr "Fehler: Sekundären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3496
msgid "Error: DNS restore 1st"
msgstr "Fehler: DNS Wiederherstellung 1."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3496
msgid "Error: Restore Primary DNS to %s failed."
msgstr "Fehler: Primären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3559
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr "def win_netsh_read_dns_to_backup: fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3592
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""
"Fehler:\n"
"SSL Root Zertifikat für %s nicht geladen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3592
msgid "Error: SSL CA Cert #1"
msgstr "Fehler: SSL CA Cert #1"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3595
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""
"Fehler:\n"
"Ungültiges root Zertifikat für %s in:\n"
"'%s'\n"
"hash ist:\n"
"'%s'\n"
"sollte aber '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3595
msgid "Error: SSL CA Cert #2"
msgstr "Fehler: SSL CA Cert #2"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3598
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""
"Fehler:\n"
"root Zertifikat für %s nicht gefunden in:\n"
"'%s'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3598
msgid "Error: SSL CA Cert #3"
msgstr "Fehler: SSL CA Cert #3"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3787
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3811
msgid "Error: netsh.exe not found!"
msgstr "Fehler: netsh.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3826
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3850
msgid "Error: route.exe not found!"
msgstr "Fehler: route.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3866
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3878
msgid "ipconfig.exe not found!"
msgstr "ipconfig.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3918
msgid "Enter your Passphrase"
msgstr "Passwort eingeben"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3923
msgid "Save Passphrase in File?"
msgstr "Passwort in Datei speichern?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3929
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3999
msgid "Passphrase:"
msgstr "Passwort:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3977
msgid "oVPN.to Setup"
msgstr "oVPN.to Setup"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3978
msgid "Enter your oVPN.to Details"
msgstr "oVPN.to Daten eingeben:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3985
msgid "User-ID:"
msgstr "User-ID:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3992
msgid "API-Key:"
msgstr "API-Key:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3998
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""
"\n"
"\n"
"Eine sicheres Passwort eingeben um den API-Login zu verschlüsseln!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4005
msgid "Repeat:"
msgstr "Wiederholen:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4123
msgid "Debug Mode Enabled"
msgstr "Debug Modus eingeschaltet"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4123
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""
"Log Datei:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4173
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4184
msgid "Error: Update failed"
msgstr "Fehler: Update fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4230
msgid "Server Window Size"
msgstr "Server Fenster Größe"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4234
msgid "Width (pixel):"
msgstr "Breite (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4238
msgid "Height (pixel):"
msgstr "Höhe (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4242
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""
"Breite und Höhe eingeben\n"
"\n"
"Leer lassen für Standard Werte"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4289
msgid "Load Data every X seconds"
msgstr "Lade Daten jede X Sekunden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4293
msgid "seconds:"
msgstr "Sekunden:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4342
msgid "Switched to IPv4+6"
msgstr "Umgeschaltet auf IPv4+6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4342
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4361
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4361
msgid "Switched to IPv6+4"
msgstr "Umgeschaltet zu IPv6+4"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4467
msgid "API requests on: %s failed!"
msgstr "API Anfrage an: %s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4467
msgid "Error: def API_REQUEST"
msgstr "Fehler: def API_REQUEST"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4479
msgid "Invalid User-ID / API-Key or Account expired."
msgstr "Ungültige(r) User-ID / API-Key oder Account abgelaufen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4582
msgid "Error: def move_appdata"
msgstr "Fehler: def move_appdata"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4582
msgid "Move Userdata to new folder: '%s'"
msgstr "Verschiebe Benutzerdaten in neues Verzeichnis: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4618
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr "Konnte Servers Remote-IP:Port nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4627
msgid "Could not read Servers Protocol from config: %s"
msgstr "Konnte Servers Protocol nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4639
msgid "Could not read Servers Cipher from config: %s"
msgstr "Konnte Servers Cipher nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4665
msgid "Error: def load_ovpn_server"
msgstr "Fehler: def load_ovpn_server"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4665
msgid "Load openVPN Server failed"
msgstr "openVPN Server Start fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4839
msgid "Platform '%s' not supported"
msgstr "Platform '%s' nicht unterstützt"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4839
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4890
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4894
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4978
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5031
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5034
msgid "Error!"
msgstr "Fehler!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4855
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""
"openVPN Setup heruntergeladen! Hash Check: OK!\n"
"\n"
"Bitte mit folgender Datei installieren:\n"
"'%s'\n"
"\n"
"GPG überprüfen mit:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4857
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"openVPN Setup heruntergeladen, aber hash Überprüfung fehlgeschlagen!\n"
"Bitte installiere openVPN manuell!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4864
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""
"Installiere OpenVPN %s (%s) (%s)\n"
"\n"
"Starte download (~1.8 MB) von:\n"
"'%s'\n"
"nach\n"
"'%s'\n"
"\n"
"Bitte warten..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4864
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4930
msgid "Setup: openVPN"
msgstr "Setup: openVPN"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4890
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""
"Ungültiger Datei hash: %s !\n"
"localhash = '%s'\n"
"sollte sein = '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4894
msgid "Failed remove file: %s"
msgstr "Datei entfernen fehlgeschlagen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4930
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""
"OpenVPN nicht gefunden!\n"
"\n"
"Bitte openvpn.exe im nächsten Fenster auswählen!\n"
"\n"
"Wenn openVPN noch nicht installiert ist im nächsten Fenster auf abbrechen "
"klicken!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4931
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr "openvpn.exe auswählen oder Abbrechen um openVPN zu installieren"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4978
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""
"WARNUNG! Dateien konnten nicht verifiziert werden in\n"
"'%s'\n"
"\n"
"openVPN deinstallieren und oVPN Client neu starten!\n"
"\n"
"Alternativ openVPN manuell installieren:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4983
msgid "Could not detect openVPN Version!"
msgstr "Konnte openVPN Version nicht ermitteln!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5007
msgid "Could not find openVPN"
msgstr "Konnte openVPN nicht finden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5031
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr "Ungültiger Hash: '%s'! is '%s' != '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5034
msgid "Invalid content '%s' in '%s'"
msgstr "Ungültiger Inhalt '%s' in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5051
msgid "arch '%s' not supported!"
msgstr "Struktur '%s' nicht unterstützt!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5252
msgid "Quit oVPN.to Client"
msgstr "oVPN.to beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5256
msgid "Do you really want to quit?"
msgstr "Wirklich beenden?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5322
msgid "Firewall Settings"
msgstr "Firewall Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5326
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Vorherige Firewall Einstellungen wiederherstellen?\n"
"\n"
"JA, vorherige wiederherstellen!\n"
"NEIN, Setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5329
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Ausgehende Verbindungen erlauben?\n"
"\n"
"JA, setze 'blockinbound,allowoutbound'!\n"
"NEIN, setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5382
msgid "Error"
msgstr "Fehler"

#~ msgid "Update every: %s sec"
#~ msgstr "Aktualisiere jede: %s Sekunden"

#~ msgid "Refresh Window"
#~ msgstr "Fenster aktualisieren"

#~ msgid "Systray Menu -> Updates -> 'Load Account Info' [disabled]"
#~ msgstr "Tray Menü -> Updates -> 'Lade Konto Informationen' [Aus]"

#~ msgid "Load Account Info %s"
#~ msgstr "Lade Konto Informationen %s"

#~ msgid "def check_config_folders: failed"
#~ msgstr "def check_config_folders: fehlgeschlagen"

#~ msgid "def read_options_file: failed!"
#~ msgstr "def read_options_file: Fehlgeschlagen!"

#~ msgid "Invalid characters in self.WIN_TAP_DEVICE = '%s'"
#~ msgstr "Ungültige Zeichen in self.WIN_TAP_DEVICE = '%s'"

#~ msgid "def inThread_timer_check_certdl: extraction failed"
#~ msgstr "def inThread_timer_check_certdl: Extraktion fehlgeschlagen"

#~ msgid "Error: oVPN Update failed!"
#~ msgstr "Fehler: oVPN Update fehlgeschlagen!"

#~ msgid "def inThread_timer_check_certdl: downloading certs failed"
#~ msgstr "def inThread_timer_check_certdl: Zertifikat download fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): fehlgeschlagen"

#~ msgid "def inThread_timer_check_certdl: failed"
#~ msgstr "def inThread_timer_check_certdl: fehlgeschlagen"

#~ msgid "Files missing: '%s' % (self.ovpn_server_dir)"
#~ msgstr "Fehlende Datei: '%s' % (self.ovpn_server_dir)"

#~ msgid ""
#~ "def inThread_spawn_openvpn_process: Could not start Windows Firewall!"
#~ msgstr ""
#~ "def inThread_spawn_openvpn_process: Windows Firewall konnte nicht "
#~ "gestartet werden!"

#~ msgid "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"
#~ msgstr "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"

#~ msgid "def win_ipconfig_flushdns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_flushdns: ipconfig.exe not found!"

#~ msgid "def win_ipconfig_displaydns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_displaydns: ipconfig.exe not found!"

#~ msgid "Error: API-Request"
#~ msgstr "Fehler: API-Request"

#~ msgid "def API_REQUEST: requests error on: %s failed!"
#~ msgstr "def API_REQUEST: requests error on: %s fehlgeschlagen!"

#~ msgid "def API_REQUEST: self.curldata = '%s'"
#~ msgstr "def API_REQUEST: self.curldata = '%s'"

#~ msgid "Move Userdata to new folder!"
#~ msgstr "Verschiebe Nutzer Daten in neues Verzeichnis!"

#~ msgid "def move_appdata: '%s'"
#~ msgstr "def move_appdata: '%s'"

#~ msgid "def load_ovpn_server: failed"
#~ msgstr "def load_ovpn_server: fehlgeschlagen"

#~ msgid "def win_detect_openvpn: failed"
#~ msgstr "def win_detect_openvpn: fehlgeschlagen"

#~ msgid "Error: WINDIR '%s' not found!"
#~ msgstr "Fehler: WINDIR '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_NETSH_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_NETSH_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_ROUTE_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_ROUTE_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_IPCONFIG_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_IPCONFIG_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_TASKKILL_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_TASKKILL_EXE '%s' nicht gefunden!"

#~ msgid "def check_winapp_dir could not create app_dir: %s"
#~ msgstr "def check_winapp_dir konnte App Verzeichnis nicht anlegen: %s"
