# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2016-07-14 22:05+0200\n"
"PO-Revision-Date: 2016-07-14 22:06+0200\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.8\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr "Update fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4077
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4087
msgid "Could not connect to %s"
msgstr "Verbindung zu %s fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:259
msgid "Operating System not supported: %s"
msgstr "Betriebssystem wird nicht unterstützt: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Copy old appdata to new folder failed!"
msgstr "Kopiere \"appdata\" in neues Verzeichnis fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:274
msgid "Error: def win_pre1_check_app_dir()"
msgstr "Fehler: def win_pre1_check_app_dir()"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:285
msgid "Could not create app_dir: %s"
msgstr "Konnte App Verzeichnis nicht anlegen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:307
msgid "Select User-ID failed!"
msgstr "User-ID Auswahl fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:370
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:373
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
msgid "Error: '%s' not found!"
msgstr "Fehler: '%s' nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:399
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""
"Sperr Datei konnte nicht entfernt werden.\n"
"Sperr Datei selbst ist gesperrt. Läuft eine weitere oVPN Client Instanz?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""
"Anlegen von API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr "Erzeugen der Konfigurationsverzeichnisse fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Error: def read_options_file"
msgstr "Fehler: def read_options_file"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:662
msgid "Read config file failed!"
msgstr "Lesen der Konfigurationsdatei fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:788
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with "
"Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""
"Konnte die Interfaces mit netsh.exe nicht auslesen. Kontaktiere support@ovpn."
"to mit Error-ID:\n"
"ADAPTERS[1]=(%s)\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:823
msgid ""
"Could not read your Network Interfaces! Please install OpenVPN or check if "
"your TAP-Adapter is really enabled and driver installed."
msgstr ""
"Konnte Netzwerk Adapter nicht auslesen! Bitte installiere openVPN oder "
"überprüfe ob der TAP Adapter installiert und aktiviert ist."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:854
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr "Kein openVPN TAP Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:868
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""
"Mehrere TAP Adapter gefunden!\n"
"\n"
"Bitte den zu benutzenden Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:884
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"Kein openVPN TAP Adapter gefunden!\n"
"Bitte openVPN installieren!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:889
msgid "Invalid characters in '%s'"
msgstr "Ungültige Zeichen in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:905
msgid "Choose your External Network Adapter!"
msgstr "Netzwerk Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:923
msgid "No Network Adapter found!"
msgstr "Keine Netzwerk Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:938
msgid "Please select your User-ID!"
msgstr "Bitte User-ID auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1048
msgid "Choose App Theme"
msgstr "App-Thema auswählen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1088
msgid "Disconnect %s"
msgstr "Trennen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1092
msgid "Connect to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1100
msgid "Remove AutoConnect: %s"
msgstr "Automatisch verbinden entfernen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1104
msgid "Set AutoConnect: %s"
msgstr "Setze automatisch verbinden: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1119
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1511
msgid "[enabled]"
msgstr "[Ein]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1121
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1513
msgid "[disabled]"
msgstr "[Aus]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1122
msgid "Load extended Server-View %s"
msgstr "Lade erweitertes Server Fenster %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1135
msgid "Set Server-View Size [%sx%s]"
msgstr "Setze Server Fenster Größe [%sx%s]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1144
msgid "Refresh Window"
msgstr "Fenster aktualisieren"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1162
msgid "Change DNS"
msgstr "DNS wechseln"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1169
msgid "Primary DNS: %s (%s)"
msgstr "Primärer DNS: %s (%s)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1179
msgid "Secondary DNS: %s (%s)"
msgstr "Sekundärer DNS: %s (%s)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1212
msgid "Primary DNS '%s' @ %s"
msgstr "Primärer DNS '%s' @ %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1215
msgid "Set Primary DNS"
msgstr "Setze primären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1221
msgid "Secondary DNS '%s' @ %s"
msgstr "Sekundärer DNS '%s' @ %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1224
msgid "Set Secondary DNS"
msgstr "Setze sekundären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1316
msgid "Checking for Updates!"
msgstr "Nach Updates suchen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1319
msgid "Disconnected! Have a nice and anonymous day!"
msgstr "Nicht verbunden! Hab einen schönen und anonymen Tag!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1333
msgid "Connecting to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1339
msgid "Testing connection to %s"
msgstr "Teste Verbindung zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1354
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr "Verbunden zu %s [%s]:%s (%s) [ %s ] (%s / %s ms)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1495
msgid "Options"
msgstr "Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1502
msgid "Select Network Adapter"
msgstr "Netzwerk Adapter wählen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1514
msgid "DEBUG Mode %s"
msgstr "DEBUG Modus %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1523
msgid "Set App Theme [%s]"
msgstr "Setze App Thema [%s]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1535
msgid "IPv6 Options"
msgstr "IPv6 Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1539
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr "Auswählen: IPv4 Eintritt Server mit Ausgang nach IPv4 (standard)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1543
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr "Auswählen: IPv4 Eintritts Server mit Ausgang nach IPv4 + IPv6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1561
msgid "Firewall"
msgstr "Firewall"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1567
msgid "Restore Firewall Backups"
msgstr "Firewall Einstellungen wiederherstellen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1589
msgid "Updates"
msgstr "Updates"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1593
msgid "Normal Config Update"
msgstr "Normales Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1597
msgid "Forced Config Update"
msgstr "Erzwungenes Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1607
msgid "Reset API Login"
msgstr "API Login zurücksetzen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1612
msgid "Clear Passphrase from RAM"
msgstr "Passwort aus dem Speicher löschen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1616
msgid "Clear Passphrase from CFG"
msgstr "Passwort aus der Konfiguration löschen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1677
msgid " [ disconnect ]"
msgstr "[ trennen ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1720
msgid "Close Servers"
msgstr "Server Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1723
msgid "Servers"
msgstr "Server Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1733
msgid "Close Account"
msgstr "Konto Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1735
msgid "Account"
msgstr "Konto Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1745
msgid "Close Settings"
msgstr "Einstellungen schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1747
msgid "Settings"
msgstr "Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1758
msgid "About"
msgstr "Über"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1766
msgid "Quit"
msgstr "Beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1808
msgid "oVPN Server Update"
msgstr "oVPN Server Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1855
msgid "Certificates and Configs updated!"
msgstr "Zertifikate und Konfiguration erneuert!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1855
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
msgid "oVPN Update OK!"
msgstr "oVPN Update OK!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1858
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1860
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1863
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1871
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
msgid "Error: def inThread_timer_check_certdl"
msgstr "Fehler: def inThread_timer_check_certdl"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1858
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1860
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1863
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1865
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1871
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1873
msgid "oVPN Update failed"
msgstr "oVPN Update fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1868
msgid "No update needed!"
msgstr "Kein Update nötig!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2117
msgid "oVPN Server - %s"
msgstr "oVPN Server - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2189
msgid "oVPN Server [ %s ]"
msgstr "oVPN Server [ %s ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2324
msgid "oVPN Account - %s"
msgstr "oVPN Konto - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2344
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr "Einstellungen -> Updates: Lade Konto Informationen [AUS]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2346
msgid "No data loaded! Retry in few seconds..."
msgstr "Keine Daten geladen! Bitte in ein paar Sekunden erneut probieren..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2443
msgid "oVPN Settings - %s"
msgstr "oVPN Einstellungen - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2451
msgid "Windows Firewall Settings\n"
msgstr "Windows Firewall Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2458
msgid " Firewall "
msgstr "Firewall"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2465
msgid "Network Adapter Settings\n"
msgstr "Netzwerk Adapter Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2468
msgid " Network "
msgstr "Netzwerk"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2475
msgid "Update Settings\n"
msgstr "Einstellungen updaten\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2478
msgid " Updates "
msgstr " Updates "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2496
msgid "Use Windows Firewall (default: ON) "
msgstr "Windows Firewall benutzen (standard: EIN) "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2526
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr "TAP-Adapter ausgehend blocken (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2557
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr "Internet sperren bei Verbindungstrennung oder Beenden (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2585
msgid "Disable FW question on Quit (default: ON)"
msgstr "Firewall Abfrage beim Beenden abschalten (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2613
msgid "Clear Rules on Connect (default: OFF)"
msgstr "Regeln löschen beim verbinden (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2633
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2663
msgid "Could not export Windows Firewall Backup!"
msgstr "Konnte Windows Firewall Sicherung nicht exportieren!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2633
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2663
msgid "Error: Windows Firewall Backup failed"
msgstr "Fehler: Windows Firewall Sicherung fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2643
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr "Sicherung/Wiederherstellung bei Start und Beenden (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2673
msgid "DNS Leak Protection (default: ON)"
msgstr "DNS Leck Schutz (standard: EIN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2702
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr "Deaktiviere '%s' bei Trennung (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2730
msgid "Update Configs on Start (default: OFF)"
msgstr "Konfigs beim starten updaten (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2755
msgid "Load Account Info (default: OFF)"
msgstr "Lade Konto Informationen (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3070
msgid "Error: Certs not found!"
msgstr "Fehler: Zertifikate nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3070
msgid "Files missing: '%s'"
msgstr "Fehlende Dateien: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Could not start Windows Firewall!"
msgstr "Konnte die Windows Firewall nicht starten!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3096
msgid "Error: def inThread_spawn_openvpn_process"
msgstr "Fehler: def inThread_spawn_openvpn_process"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3402
msgid "Error: DNS restore 2nd"
msgstr "Fehler: DNS Wiederherstellung 2."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3402
msgid "Error: Restore Secondary DNS to %s failed."
msgstr "Fehler: Sekundären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3405
msgid "Error: DNS restore 1st"
msgstr "Fehler: DNS Wiederherstellung 1."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3405
msgid "Error: Restore Primary DNS to %s failed."
msgstr "Fehler: Primären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3468
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr "def win_netsh_read_dns_to_backup: fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3501
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""
"Fehler:\n"
"SSL Root Zertifikat für %s nicht geladen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3501
msgid "Error: SSL CA Cert #1"
msgstr "Fehler: SSL CA Cert #1"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""
"Fehler:\n"
"Ungültiges root Zertifikat für %s in:\n"
"'%s'\n"
"hash ist:\n"
"'%s'\n"
"sollte aber '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3504
msgid "Error: SSL CA Cert #2"
msgstr "Fehler: SSL CA Cert #2"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""
"Fehler:\n"
"root Zertifikat für %s nicht gefunden in:\n"
"'%s'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3507
msgid "Error: SSL CA Cert #3"
msgstr "Fehler: SSL CA Cert #3"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3696
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3720
msgid "Error: netsh.exe not found!"
msgstr "Fehler: netsh.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3735
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3759
msgid "Error: route.exe not found!"
msgstr "Fehler: route.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3775
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3787
msgid "ipconfig.exe not found!"
msgstr "ipconfig.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3823
msgid "Enter your Passphrase"
msgstr "Paßphrase eingeben"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3828
msgid "Save Passphrase in File?"
msgstr "Paßphrase in Datei speichern?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3834
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3910
msgid "Passphrase:"
msgstr "Paßphrase:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3888
msgid "oVPN.to Setup"
msgstr "oVPN.to Setup"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3889
msgid "Enter your oVPN.to Details"
msgstr "oVPN.to Daten eingeben:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3896
msgid "User-ID:"
msgstr "User-ID:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3903
msgid "API-Key:"
msgstr "API-Key:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3909
msgid ""
"\n"
"\n"
"Enter a secure passphrase to encrypt your API-Login!"
msgstr ""
"\n"
"\n"
"Eine sichere Paßphrase eingeben um den API-Login zu verschlüsseln!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3916
msgid "Repeat:"
msgstr "Wiederholen:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4028
msgid "Debug Mode Enabled"
msgstr "Debug Modus eingeschaltet"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4028
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""
"Log Datei:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4077
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4087
msgid "Error: Update failed"
msgstr "Fehler: Update fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4130
msgid "Server Window Size"
msgstr "Server Fenster Größe"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4134
msgid "Width (pixel):"
msgstr "Breite (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4138
msgid "Height (pixel):"
msgstr "Höhe (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4142
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""
"Breite und Höhe eingeben\n"
"\n"
"Leer lassen für Standard Werte"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4198
msgid "Switched to IPv4+6"
msgstr "Umgeschaltet auf IPv4+6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4198
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4216
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4216
msgid "Switched to IPv6+4"
msgstr "Umgeschaltet zu IPv6+4"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4320
msgid "API requests on: %s failed!"
msgstr "API Anfrage an: %s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4320
msgid "Error: def API_REQUEST"
msgstr "Fehler: def API_REQUEST"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4332
msgid "Invalid User-ID / API-Key or Account expired."
msgstr "Ungültige(r) User-ID / API-Key oder Account abgelaufen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4432
msgid "Error: def move_appdata"
msgstr "Fehler: def move_appdata"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4432
msgid "Move Userdata to new folder: '%s'"
msgstr "Verschiebe Benutzerdaten in neues Verzeichnis: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4468
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr "Konnte Servers Remote-IP:Port nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4477
msgid "Could not read Servers Protocol from config: %s"
msgstr "Konnte Servers Protocol nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4489
msgid "Could not read Servers Cipher from config: %s"
msgstr "Konnte Servers Cipher nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4515
msgid "Error: def load_ovpn_server"
msgstr "Fehler: def load_ovpn_server"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4515
msgid "Load openVPN Server failed"
msgstr "openVPN Server Start fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4687
msgid "Platform '%s' not supported"
msgstr "Platform '%s' nicht unterstützt"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4687
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4738
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4742
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4879
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4882
msgid "Error!"
msgstr "Fehler!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4703
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""
"openVPN Setup heruntergeladen! Hash Check: OK!\n"
"\n"
"Bitte mit folgender Datei installieren:\n"
"'%s'\n"
"\n"
"GPG überprüfen mit:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4705
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"openVPN Setup heruntergeladen, aber hash Überprüfung fehlgeschlagen!\n"
"Bitte installiere openVPN manuell!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4712
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""
"Installiere OpenVPN %s (%s) (%s)\n"
"\n"
"Starte download (~1.8 MB) von:\n"
"'%s'\n"
"nach\n"
"'%s'\n"
"\n"
"Bitte warten..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4712
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4778
msgid "Setup: openVPN"
msgstr "Setup: openVPN"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4738
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""
"Ungültiger Datei hash: %s !\n"
"localhash = '%s'\n"
"sollte sein = '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4742
msgid "Failed remove file: %s"
msgstr "Datei entfernen fehlgeschlagen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4778
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""
"OpenVPN nicht gefunden!\n"
"\n"
"Bitte openvpn.exe im nächsten Fenster auswählen!\n"
"\n"
"Wenn openVPN noch nicht installiert ist im nächsten Fenster auf abbrechen "
"klicken!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4779
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr "openvpn.exe auswählen oder Abbrechen um openVPN zu installieren"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4826
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""
"WARNUNG! Dateien konnten nicht verifiziert werden in\n"
"'%s'\n"
"\n"
"openVPN deinstallieren und oVPN Client neu starten!\n"
"\n"
"Alternativ openVPN manuell installieren:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4831
msgid "Could not detect openVPN Version!"
msgstr "Konnte openVPN Version nicht ermitteln!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4855
msgid "Could not find openVPN"
msgstr "Konnte openVPN nicht finden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4879
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr "Ungültiger Hash: '%s'! is '%s' != '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4882
msgid "Invalid content '%s' in '%s'"
msgstr "Ungültiger Inhalt '%s' in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4899
msgid "arch '%s' not supported!"
msgstr "Struktur '%s' nicht unterstützt!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5100
msgid "Quit oVPN.to Client"
msgstr "oVPN.to beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5104
msgid "Do you really want to quit?"
msgstr "Wirklich beenden?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5170
msgid "Firewall Settings"
msgstr "Firewall Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5174
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Vorherige Firewall Einstellungen wiederherstellen?\n"
"\n"
"JA, vorherige wiederherstellen!\n"
"NEIN, Setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5177
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Ausgehende Verbindungen erlauben?\n"
"\n"
"JA, setze 'blockinbound,allowoutbound'!\n"
"NEIN, setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5230
msgid "Error"
msgstr "Fehler"

#~ msgid "Systray Menu -> Updates -> 'Load Account Info' [disabled]"
#~ msgstr "Tray Menü -> Updates -> 'Lade Konto Informationen' [Aus]"

#~ msgid "Load Account Info %s"
#~ msgstr "Lade Konto Informationen %s"

#~ msgid "def check_config_folders: failed"
#~ msgstr "def check_config_folders: fehlgeschlagen"

#~ msgid "def read_options_file: failed!"
#~ msgstr "def read_options_file: Fehlgeschlagen!"

#~ msgid "Invalid characters in self.WIN_TAP_DEVICE = '%s'"
#~ msgstr "Ungültige Zeichen in self.WIN_TAP_DEVICE = '%s'"

#~ msgid "def inThread_timer_check_certdl: extraction failed"
#~ msgstr "def inThread_timer_check_certdl: Extraktion fehlgeschlagen"

#~ msgid "Error: oVPN Update failed!"
#~ msgstr "Fehler: oVPN Update fehlgeschlagen!"

#~ msgid "def inThread_timer_check_certdl: downloading certs failed"
#~ msgstr "def inThread_timer_check_certdl: Zertifikat download fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): fehlgeschlagen"

#~ msgid "def inThread_timer_check_certdl: failed"
#~ msgstr "def inThread_timer_check_certdl: fehlgeschlagen"

#~ msgid "Files missing: '%s' % (self.ovpn_server_dir)"
#~ msgstr "Fehlende Datei: '%s' % (self.ovpn_server_dir)"

#~ msgid ""
#~ "def inThread_spawn_openvpn_process: Could not start Windows Firewall!"
#~ msgstr ""
#~ "def inThread_spawn_openvpn_process: Windows Firewall konnte nicht "
#~ "gestartet werden!"

#~ msgid "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"
#~ msgstr "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"

#~ msgid "def win_ipconfig_flushdns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_flushdns: ipconfig.exe not found!"

#~ msgid "def win_ipconfig_displaydns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_displaydns: ipconfig.exe not found!"

#~ msgid "Error: API-Request"
#~ msgstr "Fehler: API-Request"

#~ msgid "def API_REQUEST: requests error on: %s failed!"
#~ msgstr "def API_REQUEST: requests error on: %s fehlgeschlagen!"

#~ msgid "def API_REQUEST: self.curldata = '%s'"
#~ msgstr "def API_REQUEST: self.curldata = '%s'"

#~ msgid "Move Userdata to new folder!"
#~ msgstr "Verschiebe Nutzer Daten in neues Verzeichnis!"

#~ msgid "def move_appdata: '%s'"
#~ msgstr "def move_appdata: '%s'"

#~ msgid "def load_ovpn_server: failed"
#~ msgstr "def load_ovpn_server: fehlgeschlagen"

#~ msgid "def win_detect_openvpn: failed"
#~ msgstr "def win_detect_openvpn: fehlgeschlagen"

#~ msgid "Error: WINDIR '%s' not found!"
#~ msgstr "Fehler: WINDIR '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_NETSH_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_NETSH_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_ROUTE_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_ROUTE_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_IPCONFIG_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_IPCONFIG_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_TASKKILL_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_TASKKILL_EXE '%s' nicht gefunden!"

#~ msgid "def check_winapp_dir could not create app_dir: %s"
#~ msgstr "def check_winapp_dir konnte App Verzeichnis nicht anlegen: %s"
