# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2016-07-16 03:25+0200\n"
"PO-Revision-Date: 2016-07-16 03:25+0200\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: de_DE\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.8\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
msgid "Update failed!"
msgstr "Update fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:65
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3913
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3923
msgid "Could not connect to %s"
msgstr "Verbindung zu %s fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:253
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:255
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:257
msgid "Operating System not supported: %s"
msgstr "Betriebssystem wird nicht unterstützt: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:272
msgid "Copy old appdata to new folder failed!"
msgstr "Kopiere \"appdata\" in neues Verzeichnis fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:272
msgid "Error: def win_pre1_check_app_dir()"
msgstr "Fehler: def win_pre1_check_app_dir()"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:283
msgid "Could not create app_dir: %s"
msgstr "Konnte App Verzeichnis nicht anlegen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:310
msgid "Select User-ID failed!"
msgstr "User-ID Auswahl fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:376
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:379
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:382
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:385
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:388
msgid "Error: '%s' not found!"
msgstr "Fehler: '%s' nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:405
msgid ""
"Could not remove lock file.\n"
"File itself locked because another oVPN Client instance running?"
msgstr ""
"Sperr Datei konnte nicht entfernt werden.\n"
"Sperr Datei selbst ist gesperrt. Läuft eine weitere oVPN Client Instanz?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:450
msgid ""
"Creating API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s failed!"
msgstr ""
"Anlegen von API-DIRS\n"
"%s \n"
"%s \n"
"%s \n"
"%s \n"
"%s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:452
msgid "Creating config Folders failed"
msgstr "Erzeugen der Konfigurationsverzeichnisse fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:652
msgid "Error: def read_options_file"
msgstr "Fehler: def read_options_file"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:652
msgid "Read config file failed!"
msgstr "Lesen der Konfigurationsdatei fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:780
msgid ""
"Error reading your Interfaces from netsh.exe. Contact support@ovpn.to with "
"Error-ID:\n"
"ADAPTERS[1]=(%s)\n"
msgstr ""
"Konnte die Interfaces mit netsh.exe nicht auslesen. Kontaktiere support@ovpn."
"to mit Error-ID:\n"
"ADAPTERS[1]=(%s)\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:815
msgid ""
"Could not read your Network Interfaces! Please install OpenVPN or check if "
"your TAP-Adapter is really enabled and driver installed."
msgstr ""
"Konnte Netzwerk Adapter nicht auslesen! Bitte installiere openVPN oder "
"überprüfe ob der TAP Adapter installiert und aktiviert ist."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:846
msgid "No OpenVPN TAP-Windows Adapter found!"
msgstr "Kein openVPN TAP Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:860
msgid ""
"Multiple TAPs found!\n"
"\n"
"Please select your TAP Adapter!"
msgstr ""
"Mehrere TAP Adapter gefunden!\n"
"\n"
"Bitte den zu benutzenden Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:876
msgid ""
"No OpenVPN TAP-Adapter found!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"Kein openVPN TAP Adapter gefunden!\n"
"Bitte openVPN installieren!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:881
msgid "Invalid characters in '%s'"
msgstr "Ungültige Zeichen in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:897
msgid "Choose your External Network Adapter!"
msgstr "Netzwerk Adapter auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:915
msgid "No Network Adapter found!"
msgstr "Keine Netzwerk Adapter gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:930
msgid "Please select your User-ID!"
msgstr "Bitte User-ID auswählen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:977
msgid "Disconnect %s"
msgstr "Trennen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:981
msgid "Connect to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:989
msgid "Remove AutoConnect: %s"
msgstr "Automatisch verbinden entfernen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:993
msgid "Set AutoConnect: %s"
msgstr "Setze automatisch verbinden: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1008
msgid "[enabled]"
msgstr "[Ein]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1010
msgid "[disabled]"
msgstr "[Aus]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1011
msgid "Load Server Information %s"
msgstr "Lade Server Informationen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1024
msgid "Set Server-View Size [%sx%s]"
msgstr "Setze Server Fenster Größe [%sx%s]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1031
msgid "Update every: %s seconds"
msgstr "Aktualisiere jede: %s Sekunden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1051
msgid "Change DNS"
msgstr "DNS wechseln"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1125
msgid "Set Primary DNS"
msgstr "Setze primären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1135
msgid "Set Secondary DNS"
msgstr "Setze sekundären DNS"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1243
msgid "Checking for Updates!"
msgstr "Nach Updates suchen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1246
msgid "Disconnected! Have a nice and anonymous day!"
msgstr "Nicht verbunden! Hab einen schönen und anonymen Tag!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1260
msgid "Connecting to %s"
msgstr "Verbinde zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1266
msgid "Testing connection to %s"
msgstr "Teste Verbindung zu %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1281
msgid "Connected to %s [%s]:%s (%s) [ %s ] (%s / %s ms)"
msgstr "Verbunden zu %s [%s]:%s (%s) [ %s ] (%s / %s ms)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1413
msgid "Options"
msgstr "Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1420
msgid "Select Network Adapter"
msgstr "Netzwerk Adapter wählen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1436
msgid "IPv6 Options"
msgstr "IPv6 Optionen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1440
msgid "Select: IPv4 Entry Server with Exit to IPv4 (standard)"
msgstr "Auswählen: IPv4 Eintritt Server mit Ausgang nach IPv4 (standard)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1444
msgid "Select: IPv4 Entry Server with Exits to IPv4 + IPv6"
msgstr "Auswählen: IPv4 Eintritts Server mit Ausgang nach IPv4 + IPv6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1463
msgid "Firewall"
msgstr "Firewall"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1468
msgid "Restore Firewall Backups"
msgstr "Firewall Einstellungen wiederherstellen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1536
msgid " [ disconnect ]"
msgstr "[ trennen ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1579
msgid "Close Servers"
msgstr "Server Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1582
msgid "Servers"
msgstr "Server Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1592
msgid "Close Account"
msgstr "Konto Fenster schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1594
msgid "Account"
msgstr "Konto Fenster"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1604
msgid "Close Settings"
msgstr "Einstellungen schließen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1606
msgid "Settings"
msgstr "Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1617
msgid "About"
msgstr "Über"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1625
msgid "Quit"
msgstr "Beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1681
msgid "Certificates and Configs updated!"
msgstr "Zertifikate und Konfiguration erneuert!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1681
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1694
msgid "oVPN Update OK!"
msgstr "oVPN Update OK!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1684
msgid "Extraction failed!"
msgstr "Entpacken fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1684
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1686
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1689
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1691
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1699
msgid "Error: def inThread_timer_check_certdl"
msgstr "Fehler: def inThread_timer_check_certdl"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1686
msgid "Failed to download certificates"
msgstr "Fehler beim Runterladen der Zertifikate!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1689
msgid "Failed to request certificates!"
msgstr "Fehler beim Anfragen der Zertifikate!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1691
msgid "Failed to download configurations!"
msgstr "Fehler beim Runterladen der Konfigurationen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1694
msgid "No update needed!"
msgstr "Kein Update nötig!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1699
msgid "Failed to check for updates!"
msgstr "Fehler beim Prüfen auf Updates!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:1944
msgid "oVPN Server - %s"
msgstr "oVPN Server - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2016
msgid "oVPN Server [ %s ]"
msgstr "oVPN Server [ %s ]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2152
msgid "oVPN Account - %s"
msgstr "oVPN Konto - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2172
msgid "Settings -> Updates: 'Load Account Info' [disabled]"
msgstr "Einstellungen -> Updates: Lade Konto Informationen [AUS]"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2174
msgid "No data loaded! Retry in few seconds..."
msgstr "Keine Daten geladen! Bitte in ein paar Sekunden erneut probieren..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2271
msgid "oVPN Settings - %s"
msgstr "oVPN Einstellungen - %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2279
msgid "Security Settings\n"
msgstr "Sicherheits Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2288
msgid " Security "
msgstr " Sicherheit "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2295
msgid "Options\n"
msgstr "Einstellungen\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2301
msgid " Options "
msgstr " Einstellungen "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2308
msgid "Updates\n"
msgstr "Updates\n"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2312
msgid " Updates "
msgstr " Updates "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2330
msgid "Use Windows Firewall (default: ON) "
msgstr "Windows Firewall benutzen (standard: AN) "

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2360
msgid "TAP-Adapter block outbound (default: OFF)"
msgstr "TAP-Adapter ausgehend blocken (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2391
msgid "Block Internet on Disconnect or Quit (default: ON)"
msgstr "Internet sperren bei Trennung oder Beenden (standard: AN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2419
msgid "Disable FW question on Quit (default: ON)"
msgstr "Firewall Abfrage beim Beenden abschalten (standard: AN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2447
msgid "Clear Rules on Connect (default: OFF)"
msgstr "Regeln beim Verbinden löschen (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2467
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2497
msgid "Could not export Windows Firewall Backup!"
msgstr "Konnte Windows Firewall Sicherung nicht exportieren!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2467
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2497
msgid "Error: Windows Firewall Backup failed"
msgstr "Fehler: Windows Firewall Sicherung fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2477
msgid "Backup on Start / Restore on Quit (default: OFF)"
msgstr "Sicherung/Wiederherstellung bei Start und Beenden (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2507
msgid "DNS Leak Protection (default: ON)"
msgstr "DNS Leck Schutz (standard: AN)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2536
msgid "Disable '%s' on Disconnect (default: OFF)"
msgstr "Deaktiviere '%s' bei Trennung (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2564
msgid "Update Configs on Start (default: OFF)"
msgstr "Beim Start auf Konfig Update prüfen (standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2589
msgid "Load Account Info (default: OFF)"
msgstr "Lade Konto Informationen (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2623
msgid "Load Server Info (default: OFF)"
msgstr "Lade Server Informationen (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2658
msgid "Debug Mode (default: OFF)"
msgstr "Debug Modus (Standard: AUS)"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2674
msgid "Debug Mode Enabled"
msgstr "Debug Modus eingeschaltet"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2674
msgid ""
"Logfile:\n"
"'%s'"
msgstr ""
"Log Datei:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2685
msgid "Change App Theme"
msgstr "App Thema wechseln"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2697
msgid "Normal Config Update"
msgstr "Normales Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2706
msgid "Forced Config Update"
msgstr "Erzwungenes Konfigurations Update"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2715
msgid "Reset API-Login"
msgstr "API-Login zurücksetzen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2948
msgid "Please wait!"
msgstr "Bitte warten!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:2948
msgid "Update is running."
msgstr "Aktualisierung läuft."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3024
msgid "Error: Certs not found!"
msgstr "Fehler: Zertifikate nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3024
msgid "Files missing: '%s'"
msgstr "Fehlende Dateien: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3052
msgid "Could not start Windows Firewall!"
msgstr "Konnte die Windows Firewall nicht starten!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3052
msgid "Error: def inThread_spawn_openvpn_process"
msgstr "Fehler: def inThread_spawn_openvpn_process"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3358
msgid "Error: DNS restore 2nd"
msgstr "Fehler: DNS Wiederherstellung 2."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3358
msgid "Error: Restore Secondary DNS to %s failed."
msgstr "Fehler: Sekundären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3361
msgid "Error: DNS restore 1st"
msgstr "Fehler: DNS Wiederherstellung 1."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3361
msgid "Error: Restore Primary DNS to %s failed."
msgstr "Fehler: Primären DNS wiederherstellen zu %s fehlgeschlagen."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3424
msgid "def win_netsh_read_dns_to_backup: failed!"
msgstr "def win_netsh_read_dns_to_backup: fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3457
msgid ""
"Error:\n"
"SSL Root Certificate for %s not loaded %s"
msgstr ""
"Fehler:\n"
"SSL Root Zertifikat für %s nicht geladen %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3457
msgid "Error: SSL CA Cert #1"
msgstr "Fehler: SSL CA Cert #1"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3460
msgid ""
"Error:\n"
"Invalid SSL Root Certificate for %s in:\n"
"'%s'\n"
"hash is:\n"
"'%s'\n"
"but should be '%s'"
msgstr ""
"Fehler:\n"
"Ungültiges root Zertifikat für %s in:\n"
"'%s'\n"
"hash ist:\n"
"'%s'\n"
"sollte aber '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3460
msgid "Error: SSL CA Cert #2"
msgstr "Fehler: SSL CA Cert #2"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3463
msgid ""
"Error:\n"
"SSL Root Certificate for %s not found in:\n"
"'%s'!"
msgstr ""
"Fehler:\n"
"root Zertifikat für %s nicht gefunden in:\n"
"'%s'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3463
msgid "Error: SSL CA Cert #3"
msgstr "Fehler: SSL CA Cert #3"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3652
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3676
msgid "Error: netsh.exe not found!"
msgstr "Fehler: netsh.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3691
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3715
msgid "Error: route.exe not found!"
msgstr "Fehler: route.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3731
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3743
msgid "ipconfig.exe not found!"
msgstr "ipconfig.exe nicht gefunden!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3778
msgid "oVPN.to Setup"
msgstr "oVPN.to Setup"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3779
msgid "Enter your oVPN.to Details"
msgstr "oVPN.to Daten eingeben:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3788
msgid "User-ID:"
msgstr "User-ID:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3797
msgid "API-Key:"
msgstr "API-Key:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3913
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3923
msgid "Error: Update failed"
msgstr "Fehler: Update fehlgeschlagen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3968
msgid "Server Window Size"
msgstr "Server Fenster Größe"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3972
msgid "Width (pixel):"
msgstr "Breite (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3976
msgid "Height (pixel):"
msgstr "Höhe (pixel):"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:3980
msgid ""
"Enter width and height\n"
"\n"
"Leave blank for default"
msgstr ""
"Breite und Höhe eingeben\n"
"\n"
"Leer lassen für Standard Werte"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4027
msgid "Load Data every X seconds"
msgstr "Lade Daten jede X Sekunden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4031
msgid "seconds:"
msgstr "Sekunden:"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4080
msgid "Switched to IPv4+6"
msgstr "Umgeschaltet auf IPv4+6"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4080
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4099
msgid ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"
msgstr ""
"Changed Option:\n"
"\n"
"Use 'Forced Config Update' to get new configs!\n"
"\n"
"You have to join 'IPv6 Beta' on https://%s to use any IPv6 options!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4099
msgid "Switched to IPv6+4"
msgstr "Umgeschaltet zu IPv6+4"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4151
msgid "No API-Key!"
msgstr "Kein API-Key!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4151
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4182
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4193
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4205
msgid "Error: def API_REQUEST"
msgstr "Fehler: def API_REQUEST"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4182
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4205
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4486
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4543
msgid "Invalid User-ID or API-Key or Account expired!"
msgstr "Ungültige User-ID oder API-Key oder Zugang abgelaufen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4193
msgid "API requests on: %s failed!"
msgstr "API Anfrage an: %s fehlgeschlagen!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4306
msgid "Error: def move_appdata"
msgstr "Fehler: def move_appdata"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4306
msgid "Move Userdata to new folder: '%s'"
msgstr "Verschiebe Benutzerdaten in neues Verzeichnis: '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4342
msgid "Could not read Servers Remote-IP:Port from config: %s"
msgstr "Konnte Servers Remote-IP:Port nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4351
msgid "Could not read Servers Protocol from config: %s"
msgstr "Konnte Servers Protocol nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4363
msgid "Could not read Servers Cipher from config: %s"
msgstr "Konnte Servers Cipher nicht aus der Konfig auslesen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4389
msgid "Error: def load_ovpn_server"
msgstr "Fehler: def load_ovpn_server"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4389
msgid "Load openVPN Server failed"
msgstr "openVPN Server Start fehlgeschlage"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4565
msgid "Platform '%s' not supported"
msgstr "Platform '%s' nicht unterstützt"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4565
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4616
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4620
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4704
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4757
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4760
msgid "Error!"
msgstr "Fehler!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4581
msgid ""
"openVPN Setup downloaded and hash verified OK!\n"
"\n"
"Please start setup from file:\n"
"'%s'\n"
"\n"
"Verify GPG with:\n"
"'%s'"
msgstr ""
"openVPN Setup heruntergeladen! Hash Check: OK!\n"
"\n"
"Bitte mit folgender Datei installieren:\n"
"'%s'\n"
"\n"
"GPG überprüfen mit:\n"
"'%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4583
msgid ""
"openVPN Setup downloaded but hash verify failed!\n"
"Please install openVPN!\n"
"URL1: %s\n"
"URL2: %s"
msgstr ""
"openVPN Setup heruntergeladen, aber hash Überprüfung fehlgeschlagen!\n"
"Bitte installiere openVPN manuell!\n"
"URL1: %s\n"
"URL2: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4590
msgid ""
"Install OpenVPN %s (%s) (%s)\n"
"\n"
"Starting download (~1.8 MB) from:\n"
"'%s'\n"
"to\n"
"'%s'\n"
"\n"
"Please wait..."
msgstr ""
"Installiere OpenVPN %s (%s) (%s)\n"
"\n"
"Starte download (~1.8 MB) von:\n"
"'%s'\n"
"nach\n"
"'%s'\n"
"\n"
"Bitte warten..."

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4590
#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4656
msgid "Setup: openVPN"
msgstr "Setup: openVPN"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4616
msgid ""
"Invalid File hash: %s !\n"
"localhash = '%s'\n"
"but should be = '%s'"
msgstr ""
"Ungültiger Datei hash: %s !\n"
"localhash = '%s'\n"
"sollte sein = '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4620
msgid "Failed remove file: %s"
msgstr "Datei entfernen fehlgeschlagen: %s"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4656
msgid ""
"OpenVPN not found!\n"
"\n"
"Please select openvpn.exe on next window!\n"
"\n"
"If you did not install openVPN yet: click cancel on next window!"
msgstr ""
"OpenVPN nicht gefunden!\n"
"\n"
"Bitte openvpn.exe im nächsten Fenster auswählen!\n"
"\n"
"Wenn openVPN noch nicht installiert ist im nächsten Fenster auf abbrechen "
"klicken!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4657
msgid "Select openvpn.exe or Cancel to install openVPN"
msgstr "openvpn.exe auswählen oder Abbrechen um openVPN zu installieren"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4704
msgid ""
"WARNING! Failed to verify files in\n"
"'%s'\n"
"\n"
"Uninstall openVPN and restart oVPN Client Software!\n"
"\n"
"Or install openVPN from URL:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"
msgstr ""
"WARNUNG! Dateien konnten nicht verifiziert werden in\n"
"'%s'\n"
"\n"
"openVPN deinstallieren und oVPN Client neu starten!\n"
"\n"
"Alternativ openVPN manuell installieren:\n"
"%s[debug self.LAST_FAILED_CHECKFILE = '%s']"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4709
msgid "Could not detect openVPN Version!"
msgstr "Konnte openVPN Version nicht ermitteln!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4733
msgid "Could not find openVPN"
msgstr "Konnte openVPN nicht finden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4757
msgid "Invalid Hash: '%s'! is '%s' != '%s'"
msgstr "Ungültiger Hash: '%s'! is '%s' != '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4760
msgid "Invalid content '%s' in '%s'"
msgstr "Ungültiger Inhalt '%s' in '%s'"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4777
msgid "arch '%s' not supported!"
msgstr "Struktur '%s' nicht unterstützt!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4979
msgid "Quit oVPN.to Client"
msgstr "oVPN.to beenden"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:4983
msgid "Do you really want to quit?"
msgstr "Wirklich beenden?"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5049
msgid "Firewall Settings"
msgstr "Firewall Einstellungen"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5053
msgid ""
"Restore previous firewall settings?\n"
"\n"
"Press 'YES' to restore your previous firewall settings!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Vorherige Firewall Einstellungen wiederherstellen?\n"
"\n"
"JA, vorherige wiederherstellen!\n"
"NEIN, Setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5056
msgid ""
"Allow outgoing connection to internet?\n"
"\n"
"Press 'YES' to set profiles to 'blockinbound,allowoutbound'!\n"
"Press 'NO' to set profiles to 'blockinbound,blockoutbound'!"
msgstr ""
"Ausgehende Verbindungen erlauben?\n"
"\n"
"JA, setze 'blockinbound,allowoutbound'!\n"
"NEIN, setze 'blockinbound,blockoutbound'!"

#: E:\Persoenlich\ovpn-client\.\ovpn_client.py:5111
msgid "Error"
msgstr "Fehler"

#~ msgid "Updates"
#~ msgstr "Updates"

#~ msgid "Reset API Login"
#~ msgstr "API Login zurücksetzen"

#~ msgid "oVPN Server Update"
#~ msgstr "oVPN Server Update"

#~ msgid "API-Login failed! Invalid User-ID or API-Key or Account expired!"
#~ msgstr "Ungültige User-ID oder API-Key oder Zugang abgelaufen!"

#~ msgid "Error: def load_accinfo_from_remote"
#~ msgstr "Error: def load_accinfo_from_remote"

#~ msgid "Clear Passphrase from RAM"
#~ msgstr "Passwort aus dem Speicher löschen"

#~ msgid "Clear Passphrase from CFG"
#~ msgstr "Passwort aus der Konfiguration löschen"

#~ msgid "oVPN Update failed"
#~ msgstr "oVPN Update fehlgeschlagen"

#~ msgid "Enter your Passphrase"
#~ msgstr "Passwort eingeben"

#~ msgid "Save Passphrase in File?"
#~ msgstr "Passwort in Datei speichern?"

#~ msgid "Passphrase:"
#~ msgstr "Passwort:"

#~ msgid ""
#~ "\n"
#~ "\n"
#~ "Enter a secure passphrase to encrypt your API-Login!"
#~ msgstr ""
#~ "\n"
#~ "\n"
#~ "Eine sicheres Passwort eingeben um den API-Login zu verschlüsseln!"

#~ msgid "Repeat:"
#~ msgstr "Wiederholen:"

#~ msgid "Invalid User-ID / API-Key or Account expired."
#~ msgstr "Ungültige(r) User-ID / API-Key oder Account abgelaufen."

#~ msgid "Primary DNS '%s' @ %s"
#~ msgstr "Primärer DNS '%s' @ %s"

#~ msgid "Secondary DNS '%s' @ %s"
#~ msgstr "Sekundärer DNS '%s' @ %s"

#~ msgid "Primary DNS: %s (%s)"
#~ msgstr "Primärer DNS: %s (%s)"

#~ msgid "Secondary DNS: %s (%s)"
#~ msgstr "Sekundärer DNS: %s (%s)"

#~ msgid "Load extended Server-View %s"
#~ msgstr "Lade Server Informationen %s"

#~ msgid "Change Theme"
#~ msgstr "App Thema wechseln"

#~ msgid "Choose App Theme"
#~ msgstr "App-Thema auswählen"

#~ msgid "DEBUG Mode %s"
#~ msgstr "DEBUG Modus %s"

#~ msgid "Set App Theme [%s]"
#~ msgstr "Setze App Thema [%s]"

#~ msgid "Windows Firewall Settings\n"
#~ msgstr "Windows Firewall Einstellungen\n"

#~ msgid " Firewall "
#~ msgstr " Firewall "

#~ msgid "Network Adapter Settings\n"
#~ msgstr "Netzwerk Adapter Einstellungen\n"

#~ msgid " Network "
#~ msgstr " Netzwerk "

#~ msgid "Update Settings\n"
#~ msgstr "Update Einstellungen \n"

#~ msgid "Update every: %s sec"
#~ msgstr "Aktualisiere jede: %s Sekunden"

#~ msgid "Refresh Window"
#~ msgstr "Fenster aktualisieren"

#~ msgid "Systray Menu -> Updates -> 'Load Account Info' [disabled]"
#~ msgstr "Tray Menü -> Updates -> 'Lade Konto Informationen' [Aus]"

#~ msgid "Load Account Info %s"
#~ msgstr "Lade Konto Informationen %s"

#~ msgid "def check_config_folders: failed"
#~ msgstr "def check_config_folders: fehlgeschlagen"

#~ msgid "def read_options_file: failed!"
#~ msgstr "def read_options_file: Fehlgeschlagen!"

#~ msgid "Invalid characters in self.WIN_TAP_DEVICE = '%s'"
#~ msgstr "Ungültige Zeichen in self.WIN_TAP_DEVICE = '%s'"

#~ msgid "def inThread_timer_check_certdl: extraction failed"
#~ msgstr "def inThread_timer_check_certdl: Extraktion fehlgeschlagen"

#~ msgid "Error: oVPN Update failed!"
#~ msgstr "Fehler: oVPN Update fehlgeschlagen!"

#~ msgid "def inThread_timer_check_certdl: downloading certs failed"
#~ msgstr "def inThread_timer_check_certdl: Zertifikat download fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "requestcerts): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "getconfigs): fehlgeschlagen"

#~ msgid ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): failed"
#~ msgstr ""
#~ "def inThread_timer_check_certdl: self.API_REQUEST(API_ACTION = "
#~ "lastupdate): fehlgeschlagen"

#~ msgid "def inThread_timer_check_certdl: failed"
#~ msgstr "def inThread_timer_check_certdl: fehlgeschlagen"

#~ msgid "Files missing: '%s' % (self.ovpn_server_dir)"
#~ msgstr "Fehlende Datei: '%s' % (self.ovpn_server_dir)"

#~ msgid ""
#~ "def inThread_spawn_openvpn_process: Could not start Windows Firewall!"
#~ msgstr ""
#~ "def inThread_spawn_openvpn_process: Windows Firewall konnte nicht "
#~ "gestartet werden!"

#~ msgid "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"
#~ msgstr "def inThread_spawn_openvpn_process: self.inThread_timer_ovpn_ping"

#~ msgid "def win_ipconfig_flushdns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_flushdns: ipconfig.exe not found!"

#~ msgid "def win_ipconfig_displaydns: ipconfig.exe not found!"
#~ msgstr "def win_ipconfig_displaydns: ipconfig.exe not found!"

#~ msgid "Error: API-Request"
#~ msgstr "Fehler: API-Request"

#~ msgid "def API_REQUEST: requests error on: %s failed!"
#~ msgstr "def API_REQUEST: requests error on: %s fehlgeschlagen!"

#~ msgid "def API_REQUEST: self.curldata = '%s'"
#~ msgstr "def API_REQUEST: self.curldata = '%s'"

#~ msgid "Move Userdata to new folder!"
#~ msgstr "Verschiebe Nutzer Daten in neues Verzeichnis!"

#~ msgid "def move_appdata: '%s'"
#~ msgstr "def move_appdata: '%s'"

#~ msgid "def load_ovpn_server: failed"
#~ msgstr "def load_ovpn_server: fehlgeschlagen"

#~ msgid "def win_detect_openvpn: failed"
#~ msgstr "def win_detect_openvpn: fehlgeschlagen"

#~ msgid "Error: WINDIR '%s' not found!"
#~ msgstr "Fehler: WINDIR '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_NETSH_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_NETSH_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_ROUTE_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_ROUTE_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_IPCONFIG_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_IPCONFIG_EXE '%s' nicht gefunden!"

#~ msgid "Error: self.WIN_TASKKILL_EXE '%s' not found!"
#~ msgstr "Fehler: self.WIN_TASKKILL_EXE '%s' nicht gefunden!"

#~ msgid "def check_winapp_dir could not create app_dir: %s"
#~ msgstr "def check_winapp_dir konnte App Verzeichnis nicht anlegen: %s"
